### PR TITLE
Return single element when no n is specified in first and last

### PR DESCRIPTION
**Pull request by ameligrana**
This is more in line on how Julia works with first and last. Notice that this is breaking though when no n is provided

### CODE REVIEW

**Comment by JaredSchwartz** [comment]
Okay, I see-- because it's always returning a Vector{Vector{String}}, even when n is not provided. Your patch would return the first/last Vector{String} when n is not provided.

What about when n is provided, but n=1? Your patch would still return Vector{Vector{String}}. Maybe we do something like this instead?

```julia
function Base.first(txns::Txns, n::Integer=1)
    if n == 1
        return txns[1]
    end
    return [txns[i] for i in 1:min(n, txns.n_transactions)]
end

function Base.last(txns::Txns, n::Integer=1)
    if n == 1
        return txns[end]
    end
    return [txns[i] for i in max(1, txns.n_transactions-n+1):txns.n_transactions]
end
```

**Comment by JaredSchwartz** [comment]
Also, can you open an issue for this? I haven't had anyone else contribute yet, so I haven't written a code of conduct, but generally, I'd like to see issues before PRs.

**Comment by JaredSchwartz** [comment]
Actually, I think I'm just going to implement my solution. I have to update the tests as well, and this is a simple-enough change.

I really appreciate you taking the time to contribute though. This was a good catch!

**Comment by ameligrana** [comment]
I think that the more correct solution would still be this one, consider this behaviour with vectors:

```julia
julia> a = [1,2,3]
3-element Vector{Int64}:
 1
 2
 3

julia> first(a)
1

julia> first(a, 1)
1-element Vector{Int64}:
 1
```

**Comment by ameligrana** [comment]
If you want a suggestion on the management of the project, I would say that opening an issue is fine before a PR, but consider that this is a very simple change, and usually people don't require issues for simple fixes, and in any case, we can always discuss design changes in PRs :-)

**Comment by JaredSchwartz** [comment]
> I think that the more correct solution would still be this one, consider this behaviour with vectors:

Okay, I see your point. We'll need to update the tests to account for this change

**Comment by JaredSchwartz** [comment]
> If you want a suggestion on the management of the project, I would say that opening an issue is fine before a PR, but consider that this is a very simple change, and usually people don't require issues for simple fixes, and in any case, we can always discuss design changes in PRs :-)

I'd still like an issue first. Even if a change seems simple, it's better to discuss the change before it's written than after.

**Comment by ameligrana** [comment]
> I'd still like an issue first. Even if a change seems simple, it's better to discuss the change before it's written than after.

Sure, but let's suppose I just improve the performance of a function without changing any behavior, then this doesn't require any discussion

**Comment by JaredSchwartz** [comment]
> > I'd still like an issue first. Even if a change seems simple, it's better to discuss the change before it's written than after.
> 
> Sure, but let's suppose I just improve the performance of a function without changing any behavior, then this doesn't require any discussion

I'm not bending on this. If you find issues in the code, open an issue, not an unsolicited PR.

**Pull request merged**
